### ISSUE TITLE
Moral System

### ISSUE THREAD

**Issue by ambs02** [UQcsse3200/2024-studio-3#102]
# **Description**

At the end of the “level” players will have to make a moral decision that will impact future “levels” of gameplay. This will be a UI component that spawns a mysterious looking character, and they will give dialogue to the players, prompting them to make a moral decision in a specific amount of time. 

## SubFeature/component (optional)

- timer for moral decision to be made by player
- creating art for mysterious character
- creating dialogue for mysterious character
- creating different moral decisions scenarios (eg. put the catnip in the cats food)

# **Dependencies**

Feature ticket relies on End of Day #57

# **Milestones**

- [ ]  Create different moral scenarios (Sept. 8)
- [x] #158 (Sept. 8)
- [x] #144 (Sept. 11)
- [ ] #181
- [ ] #190

**Completion Deadline:** Sept. 13

# **Documentation**

- [Moral Decision](https://github.com/UQcsse3200/2024-studio-3/wiki/Moral-Decision)
- [Moral Decision Display](https://github.com/UQcsse3200/2024-studio-3/wiki/Moral-Decision-Display)

# **Members**
Amber Chen (@ambs02)
Nimesh Garg (@nimeshgarg)

**Comment by nimeshgarg** [comment]
Closing Ticket.
New ticket for Sprint 3 will be created with exact moral decisions as decided by story team along with different screen for each day.
