### ISSUE TITLE
Documentation of Station Entities

### ISSUE THREAD

**Issue by nuciforan0** [UQcsse3200/2024-studio-3#18]
# **Description**
**Task:** Add documentation for station entity
**Feature:** [Feature which this tasks contributes to implementing](#2)

Documentation used to explain how each component of the station entity works. 
Explains input variables, what they represent & what type they are, as well as shows details of expected outputs. 
 

# **Dependencies**

- [ ] Dependency 1 (#13)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] f (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-3/wiki/Stations#stationfactory)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by Hayden-Elliott** [comment]
Redundant
