### ISSUE TITLE
Speed boots upgrade

### ISSUE THREAD

**Issue by Joanna-Wang105** [UQcsse3200/2024-studio-3#291]
# **Description**
**Task:** [upgrading greased floor]
**Feature:** [Team 2 Upgrades](#290 )

Upgrading the game by adding greased floor so it will speed up the movement of the player (for 1 minute)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] UI Implementation 
- [x] Trigger for UI implementation 
- [x] Implementing speed boot class
- [x] Documentation 
 
**Completion Deadline:** Oct 3
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Joanna (@Joanna-Wang105 )
- Daleela (@daleelakhairil )

**Comment by jRusso03** [comment]
Could purchasing a 'shoe' upgrade for a speed boost in a kitchen be more suitable than a greased floor?

**Comment by Joanna-Wang105** [comment]
That's a great idea! Thank you!

btw the upgrade thing is similar to the moral decision one where during the day the NPC (if we can implement it) will come in and once user interact with the NPC, the game will paused and it will pop up a menu asking if you want to purchase a 'shoe' to speed up the movement of the player. This will not be used forever tho (might just be 1~2 minutes thing and it will be gone)
Also, the options will be random so it won't be "shoe" all the time. Hope this makes sense, feel free to ask us on discord :)
