### ISSUE TITLE
Fire extinguisher Interaction Bug

### ISSUE THREAD

**Issue by StrayIntellectual** [UQcsse3200/2024-studio-3#322]
## Description
Game crashes on interact with fire extinguisher
## How To Reproduce
Steps to reproduce the behaviour:
1. Start game
2. Walk to Fire extinguisher
3. Press 'E'
4. Crash :(

## Expected Behaviour
Standard fire extinguisher behaviour expected, pickup etc.

## Temporary Fix
Remove fire extinguisher from game, potentially unnecessary bloat.

**Comment by benjamin-wang1** [comment]
Fixed in the latest main (#319
