### ISSUE TITLE
benches and border collisions

### ISSUE THREAD

**Issue by Rakshit31773** [UQcsse3200/2024-studio-3#323]
# **Description**
**Task:** [Fixing Border and bench collisions](#3).

The chef gets partly inside the borders or benches, so the collisions needs fixing.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Tweak the border
- [x] Tweak the benches
 
**Completion Deadline:** Sep. 21

 
# **Member**
- Rakshit (@Rakshit31773)
- Danh (@danhdinh98)

**Comment by Sarahkhalek** [comment]
This issue was completed on the 21st of September
