### ISSUE TITLE
Game Crashes when clicking Start

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#351]
## Description
Game Crashes when clicking Start

## How To Reproduce
Steps to reproduce the behaviour:
1. Launch game
2. Click 'Start' in main menu
3. Game crashes and exits

## Expected Behaviour
Game screen should change to main game

## Temporary Fix
Comment out line 34 in `com.csse3200.game.components.station.StationItemHandlerComponent`

**Comment by Hayden-Elliott** [comment]
Cannot replicate on my end. Seeking further clarification

**Comment by Hayden-Elliott** [comment]
Version build issue on issuer end from random change to environment variables, no changes needed
