### ISSUE TITLE
Customer spawning Order Bug

### ISSUE THREAD

**Issue by AidenRichards03** [UQcsse3200/2024-studio-3#368]
## Description
Issue to ensure order dockets are being automatically generated when customers are spawned in. Must ensure orders correlate with customers order preferences.

Currently when tickets are created on customer spawn, two tickets are put onto the order docket display.

## How To Reproduce
Steps to reproduce the behaviour:
1. Start Game
2. Orders will not automatically generate when customers walk in
3. Check logs
4. See error: SEVERE: No recipe found for preference: <Insert recipe>

## Expected Behaviour
Recipes exist within the recipe files. Docket has triggers to use for recipes, recipe docket should automatically generate when called.

## Screenshots
![Screenshot 2024-09-27 at 11 50 45 PM](https://github.com/user-attachments/assets/d2e928ba-afd6-488e-bd70-1f82ea82ea28)

## Additional Context
Relies on working docket triggers which have recently been created, see #350 

This ticket will also be used to track the cleanup of NPCFactory code as a number of redundant functions have been put into the methods

## Temporary Fix
Describe any known workaround for the problem.

**Comment by abhat0** [comment]
I think this is happening because #350 isnt merged into main

**Comment by AidenRichards03** [comment]
> I think this is happening because #350 isnt merged into main

Nah even from the code in the npc factory, its creating duplicate of order tickets when it does spawn in
