### ISSUE TITLE
Customers fail to resume after pause and resume the game

### ISSUE THREAD

**Issue by ImLeiSu** [UQcsse3200/2024-studio-3#371]
##Description

Occasionally, when customer movement is paused and then resumed in the game, some customers fail to resume moving as expected.

##How To Reproduce

Go to 'Main Game'.
Press "O" that pauses customer movement.

##Expected Behaviour

All customers should resume their normal movement patterns after gameplay is resumed.

Screenshots

https://github.com/user-attachments/assets/16b70757-89c4-4b6f-a0d5-bc0d31459fe3

https://github.com/user-attachments/assets/80f61390-3809-49e0-bcf5-609e325914e4

## Additional Context
This issue does not occur consistently but has been observed several times under similar conditions, suggesting a potential issue with how pause/resume states are managed for customer entities.

##Temporary Fix

A temporary workaround is to manually close game and re-start it.

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme

you may need to install the c compiler
