### ISSUE TITLE
Station interaction behaviour

### ISSUE THREAD

**Issue by benjamin-wang1** [UQcsse3200/2024-studio-3#380]
## Description
Since the stations are placed closer together, this is inconsistent and buggy behaviour when try to interact with them when standing near multiple stations. 
Sometimes, standing next to a station and trying to press 'e' to interact with it will interact with another station that is further away instead. Other times it just won't interact at all and I have to move around a bit and spam 'e' until it works

## Expected Behaviour
The player should only be able to interact with the closest station, and should be able to interact when in range.

## Additional Context
It might be due to overlapping interaction ranges since the stations are close together. Maybe placing them more spaced out will help?

**Comment by Hayden-Elliott** [comment]
Suspected two contributing factors, the player hit box and the way closest interactable is updated. Further investigating

**Comment by Hayden-Elliott** [comment]
Fixed player hitbox but still seeing unexpected behaviour. Investigation suggests a larger architecture problem, following up with original Team for their thoughts
