### ISSUE TITLE
Fix Background Updates

### ISSUE THREAD

**Issue by amacn13** [UQcsse3200/2024-studio-3#461]
# **Description**
**Feature**: #459
Fix main game screen background to correctly update throughout an in game "day". Was a feature that was working correctly in feature branch during sprint 3 - however must have been a change to how _update_ is called in main that doesn't call this feature.

#**SubFeatures**
- Also wish to implement cheat codes to fast forward to a particular time of day

## **Examples (optional)**
- Background should change to reflect the time of day (morning, afternoon, night, etc.)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [X] Fully implement background updates + cheat code (Oct 11)
- [X] Ensure that it is working after day resets (Oct 11)

**Completion Deadline:** Oct 11

# **Documentation**
- Main Game Screen Background

# **Members**
- e.g. Alex M (@amacn13)

**Comment by Sarahkhalek** [comment]
Closed by #542
