### ISSUE TITLE
Penguin NPC clicking issues

### ISSUE THREAD

**Issue by AshHarikrishna** [UQcsse3200/2024-studio-3#522]
## Description
Although #512 seemed to be fixed, it had discrepancies when working with other laptops that had different screen sizes, making the hitbox of the penguin be in different locations. Some users would click the penguin for nothing to happen, and realise the hit box for it is in a different location

## How To Reproduce
Steps to reproduce the behaviour:
1. When Penguin has red exclamation mark
2. Click around penguin
4. Might not have any effect, or penguin hitbox not directly on penguin

## Expected Behaviour
when clicking penguin, should activate upgrade display

## Additional Context
works as expected on macbook air in full screen mode.

## Temporary Fix
For now, just going to set the activation for the penguin NPC as the U keybind

**Comment by Joanna-Wang105** [comment]
Resolved by using U keybind
