### ISSUE TITLE
Combine not working/ shown as option

### ISSUE THREAD

**Issue by Hayden-Elliott** [UQcsse3200/2024-studio-3#663]
## Description
Cannot attempt to combine on a station with correct ingredients

## How To Reproduce
Steps to reproduce the behaviour:
1. Go to day1
2. Get all ingredients
3. Put into station
4. Observe no combine

## Expected Behaviour

Ability to combine

**Comment by silagarv** [comment]
Have you put a plate in the station?

**Comment by Hayden-Elliott** [comment]
...
