### ISSUE TITLE
Customer Types

### ISSUE THREAD

**Issue by ambs02** [UQcsse3200/2024-studio-3#7]
# **Description**
Each of the customers in “Papas Animalria (PA)” will have their own specific tastes, quirks, timers and design. This ticket serves to implement a large portion of the character both as a design and as a class, we aim to implement customers as an overall class and each individual type of animal as a subclass which tailor their preferences in game. 

## SubFeature/component
 - Customer Profile 
# **Dependencies**
- Game Engine (given) 

# **Milestones**
- [x] #22
- [x] #42
- [x] #39
- [x] #40
- [x] #41

**Completion Deadline:** Aug. 28

# **Extras (optional)**
- [x] Character Arts for all diff customers

# **Documentation**
- [Entity Component System](../wiki/Entity-Component-System-(ECS))
- [Service Locator](../wiki/Service-Locator)

# **Members**
**- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
Aiden Richards (@AidenRichards03)
Marcus Baulch (@baulch-m) 
Amber CHen (@ambs02)
Nimesh Garg (@nimeshgarg)
Vansh Mittal (@V4N5HM)
Lei Su (@ImLeiSu )

**Comment by JTrenerry** [comment]
I recommend looking into [ECS](https://github.com/UQcsse3200/2024-studio-3/wiki/Entity-Component-System-(ECS)), there are also [services](https://github.com/UQcsse3200/2024-studio-3/wiki/Service-Locator) that may solve some things already for you.

**Comment by nimeshgarg** [comment]
Customer Profile will have the following. Add to the respective task ticket

### Customer Profile 
  - Name
  - System ID (to diff between same types of cust)
  - Preferences 
  - Individual wait timers 
  - Design
  - Reputation meter (unseen to player)
  - Spawn ability
